export const ROLES = {
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  EDITOR: "editor"
};

export const PERMISSIONS = {
  CREATE: "create",
  UPDATE: "update",
  DELETE: "delete",
  VIEW: "view",
  PUBLISH: "publish"
};

export const ADMIN_SECTIONS = {
  DASHBOARD: "dashboard",
  SETTINGS: "settings",
  LIBRARY: "library",
  DEPARTMENTS: "departments",
  LEADERS: "leaders",
  GROUPS: "groups",
  REPORTS: "reports",
  MEDIA: "media",
  ANNOUNCEMENTS: "announcements",
  USERS: "users",
  ACCOUNT: "account"
};

export const ALL_ADMIN_SECTIONS = Object.values(ADMIN_SECTIONS);

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.CREATE,
    PERMISSIONS.UPDATE,
    PERMISSIONS.DELETE,
    PERMISSIONS.VIEW,
    PERMISSIONS.PUBLISH
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE,
    PERMISSIONS.UPDATE,
    PERMISSIONS.DELETE,
    PERMISSIONS.VIEW,
    PERMISSIONS.PUBLISH
  ],
  [ROLES.EDITOR]: [PERMISSIONS.CREATE, PERMISSIONS.UPDATE, PERMISSIONS.VIEW]
};

export const ROLE_SECTION_ACCESS = {
  [ROLES.SUPER_ADMIN]: ALL_ADMIN_SECTIONS,
  [ROLES.ADMIN]: ALL_ADMIN_SECTIONS,
  [ROLES.EDITOR]: [
    ADMIN_SECTIONS.DASHBOARD,
    ADMIN_SECTIONS.DEPARTMENTS,
    ADMIN_SECTIONS.LEADERS,
    ADMIN_SECTIONS.GROUPS,
    ADMIN_SECTIONS.REPORTS,
    ADMIN_SECTIONS.MEDIA,
    ADMIN_SECTIONS.ANNOUNCEMENTS,
    ADMIN_SECTIONS.ACCOUNT
  ]
};

export const USER_STATUS = {
  ACTIVE: "active",
  DISABLED: "disabled"
};
